---
- hosts: localhost
  gather_facts: false
  connection: local

  tasks: 
  - name: Add a new tenant
    aci_tenant:
      host: "{{ aci_url }}"
      username: "{{ aci_user }}"
      password: "{{ aci_password }}"
      tenant: Prod 
      description: "{{ tenant_desc }}"
      state: present
      validate_certs: no
    delegate_to: localhost


